## Append samples you want in your CSV to this file as resources ##
resources:
- infrastructure_v1alpha1_proxmoxmachine.yaml
- infrastructure_v1alpha1_proxmoxcluster.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
