name: Release

on:
  release:
    types:
      - created


jobs:
  infrastructure:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: make infra-yaml VERSION=${{ github.ref_name }}
      - name: Metadata
        run: cp metadata.yaml _dist/
      - name: Upload infrastructure-components
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: _dist/*
          asset_name: infrastructure-components.yaml
          tag: ${{ github.ref }}
          file_glob: true
