name: Lint and Test

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  superlint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Lint Dockerfile, Shell scripts, YAML
        uses: super-linter/super-linter@v4
        env:
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # Linters to enable
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_YAML: true

          VALIDATE_ALL_CODEBASE: false

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Syntax
        run: |
          formatted_count=$(gofmt -s -l . | wc -l)
          if [ "${formatted_count}" -ne 0 ] ; then
            echo "Run 'go fmt github.com/noteable-io/noteable-ctl...'"
            exit 1
          fi

  test:
    strategy:
      matrix:
        go-version: [ 1.20.x ]
    runs-on: ubuntu-22.04
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -v ./... -cover
